# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0010_increase_hint_max_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='type',
            field=models.CharField(choices=[('L', 'Линейный'), ('NL', 'Нелинейный'), ('LNL', 'Линейно-нелинейный'), ('ML', 'Многолинейный')], default='L', max_length=3, verbose_name='тип'),
        ),
    ]
