# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0011_add_ml_quest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordination.Quest'),
        ),
    ]
