# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-28 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0012_quest_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['quest__title', 'order_number', 'name'], 'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
    ]
