# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0013_change_ordering_mission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='номер линии'),
        ),
    ]
